version: "3.9"

services:
  client:
    container_name: planning_poker_client
    build: 
      context: ClientApp
    
    ports:
      - "80:80"
    depends_on:
      - "api"
      
  api:
    container_name: planning_poker_api
    build: 
      context: .
      dockerfile: WebApi/Dockerfile
    
    ports:
      - "5050:5000"


