version: '3.7'

services:

  postgres:
    image: "postgres:13-alpine"
    environment: 
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: qwerty123
      PGDATA: /var/lib/postgresql/data/pgdata
    tmpfs: ["/var/lib/postgresql/data/pgdata"]
    ports: ["5432:5432"]
    command:
    - postgres
    - -c
    - max_connections=5000
    - -c
    - shared_buffers=600MB