name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: .

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    - 
      name: Login to DockerHub
      uses: docker/login-action@v1   
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }} 
          
    - 
      name: Build and push WebApi
      id: docker_build_api
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./WebApi/Dockerfile
          push: true
          tags: slavkaonline/planningpoker_api:latest
    -  
       name: Image digest
       run: echo ${{ steps.docker_build.outputs.digest }}       
    - 
      name: Build and push Client
      id: docker_build_client
      uses: docker/build-push-action@v2
      with:
          context: ./ClientApp
          file: ./ClientApp/Dockerfile
          push: true
          tags: slavkaonline/planningpoker_client:latest
   
    -
     name: Image digest
     run: echo ${{ steps.docker_build.outputs.digest }}              
      
