name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: sa
          POSTGRES_PASSWORD: qwerty123
          POSTGRES_DB: planning_poker
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Tests
      run: dotnet test ./Tests/Tests.fsproj --no-build --verbosity normal -l "console;verbosity=detailed"
    - name: Integration Tests
      run: dotnet test ./IntegrationTests/IntegrationTests.fsproj --no-build --verbosity normal -l "console;verbosity=detailed"
